mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
<<<<<<< HEAD
    - MYSQL_USER=master
    - MYSQL_PASSWORD=master_pass
    - MYSQL_DATABASE=petclinic
=======
    - MYSQL_USER=feat_2
    - MYSQL_PASSWORD=feat_2_pass
    - MYSQL_DATABASE=feat_2_db
>>>>>>> feat_2
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
